load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "voltage_logger",
    srcs = ["voltage_logger.py"],
    deps = [requirement("absl-py")],
)

py_binary(
    name = "voltage_logger_main",
    srcs = ["voltage_logger_main.py"],
    deps = [
        ":voltage_logger",
        requirement("absl-py"),
    ],
)
