module(name = "scum")

bazel_dep(
    name = "pico-sdk",
    version = "2.2.0",
)
bazel_dep(
    name = "platforms",
    version = "1.0.0",
)
bazel_dep(
    name = "rules_cc",
    version = "0.2.17",
)
bazel_dep(
    name = "rules_pkg",
    version = "1.2.0",
)
bazel_dep(
    name = "rules_python",
    version = "1.9.0",
)
bazel_dep(
    name = "rules_shell",
    version = "0.7.1",
)
bazel_dep(
    name = "toolchains_arm_gnu",
    version = "1.2.0",
)
git_override(
    module_name = "toolchains_arm_gnu",
    remote = "https://github.com/hexdae/toolchains_arm_gnu.git",
    tag = "v1.2.0",
)

# ARM GNU toolchains.
arm_toolchain = use_extension("@toolchains_arm_gnu//:extensions.bzl", "arm_toolchain")
arm_toolchain.arm_none_eabi()
use_repo(arm_toolchain, "arm_none_eabi")

# Custom toolchains.
register_toolchains("//scum/firmware/tools:all")

single_version_override(
    module_name = "pico-sdk",
    patches = ["//third_party:pico-sdk.patch"],
)

# Configure Pico SDK toolchains.
register_toolchains(
    "@pico-sdk//bazel/toolchain:linux-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:linux-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:win-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:win-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:mac-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:mac-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:mac-aarch64-rp2040",
    "@pico-sdk//bazel/toolchain:mac-aarch64-rp2350",
)

# Configure the Python toolchain.
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.13",
)

# Load pip dependencies.
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.13",
    requirements_lock = "//deps:requirements.txt",
)
use_repo(pip, "pypi")
