load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "s1p_viewer",
    srcs = ["s1p_viewer.py"],
    deps = [
        "//utils/visualization:mpl_config",
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("scikit-rf"),
    ],
)

py_binary(
    name = "s1p_viewer_main",
    srcs = ["s1p_viewer_main.py"],
    deps = [
        ":s1p_viewer",
        requirement("absl-py"),
    ],
)
