load("@pypi//:requirements.bzl", "requirement")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "scum_bootloader",
    srcs = ["scum_bootloader.py"],
    deps = [
        "//utils/serial:serial_interface",
        requirement("absl-py"),
    ],
)

py_binary(
    name = "scum_bootloader_main",
    srcs = ["scum_bootloader_main.py"],
    deps = [
        ":scum_bootloader",
        requirement("absl-py"),
    ],
)

pkg_tar(
    name = "scum_bootloader_main_tar_pkg",
    srcs = [":scum_bootloader_main"],
    extension = ".tar.gz",
    include_runfiles = True,
    strip_prefix = "/scum/utils/",
)
