load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "scum_bootloader_usb_main",
    srcs = ["scum_bootloader_usb_main.c"],
    defines = ["PICO_STDIO_DEFAULT_CRLF=0"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//pico:defs",
        "//pico/scum:bootloader",
        "//pico/scum:uart",
        "@pico-sdk//src/rp2_common:pico_platform",
        "@pico-sdk//src/rp2_common/pico_stdio",
        "@pico-sdk//src/rp2_common/pico_stdio_usb",
    ],
)

cc_binary(
    name = "scum_bootloader_wifi_main",
    srcs = ["scum_bootloader_wifi_main.c"],
    defines = ["PICO_STDIO_DEFAULT_CRLF=0"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//pico:defs",
        "//pico/scum:bootloader",
        "//pico/scum:uart",
        "//pico/wifi:env",
        "//pico/wifi:http_client",
        "//pico/wifi:lwipopts",
        "@pico-sdk//src/common/pico_time",
        "@pico-sdk//src/rp2_common:pico_platform",
        "@pico-sdk//src/rp2_common/pico_cyw43_arch",
        "@pico-sdk//src/rp2_common/pico_lwip",
        "@pico-sdk//src/rp2_common/pico_lwip:pico_lwip_http",
        "@pico-sdk//src/rp2_common/pico_stdio",
        "@pico-sdk//src/rp2_common/pico_stdio_usb",
    ],
)
