load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "bgr_main",
    srcs = ["bgr_main.py"],
    data = ["//tapeout/power/data:bgr_data"],
    deps = [
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("pandas"),
    ],
)

py_binary(
    name = "iref_main",
    srcs = ["iref_main.py"],
    data = ["//tapeout/power/data:iref_data"],
    deps = [
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("pandas"),
    ],
)

py_binary(
    name = "ldo_main",
    srcs = ["ldo_main.py"],
    data = ["//tapeout/power/data:ldo_data"],
    deps = [
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("pandas"),
    ],
)
