package(default_visibility = ["//visibility:public"])

filegroup(
    name = "single_channel_calibration_logs",
    srcs = [
        "single_channel_calibration.csv",
        "single_channel_calibration_multiple_1.csv",
        "single_channel_calibration_multiple_2.csv",
    ],
)

filegroup(
    name = "multi_channel_calibration_logs",
    srcs = [
        "multi_channel_calibration_home.txt",
        "multi_channel_calibration_swarm_1.txt",
        "multi_channel_calibration_swarm_2.txt",
    ],
)
