name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazel build //...
      - run: bazel build --platforms //pico/platform:pico2 --aspects @pico-sdk//tools:uf2_aspect.bzl%pico_uf2_aspect --output_groups=+pico_uf2_files //pico/...
      - run: bazel build --platforms //pico/platform:pico2_w --aspects @pico-sdk//tools:uf2_aspect.bzl%pico_uf2_aspect --output_groups=+pico_uf2_files //pico/...
      - run: bazel test --test_output=errors //...
