load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "scum",
    srcs = glob(["*.c"]),
    hdrs = glob(["*.h"]),
    defines = [
        "MODULE_OPTICAL",
        "MODULE_GPIO",
        "MODULE_INIT",
        "MODULE_SCM3C_HW_INTERFACE",
        "MODULE_SYS",
        "MODULE_UART",
    ],
    target_compatible_with = select({
        "//platform:scum3c": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = ["//scum/firmware/cmsis"],
    alwayslink = True,
)
